<a href="https://colab.research.google.com/github/slai2021/Data_science/blob/main/Samantha_Lai_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [ ]:
for i in range(100): #100 range 
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [ ]:
for i in range(5,8): #array of less than 8 from 5 
    print(i)

5
6
7


In [ ]:
for i in range(3): #test numbers less than 3 
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [ ]:
def square(x): #square root ***
    return x**2

In [ ]:
square(5)

25

In [ ]:
square(square(2)) #square root of 4 

16

In [ ]:
square(square(square(2))) #working with square root 


256

In [ ]:
square(123456)

15241383936

In [ ]:
square(square(5))

625

In [ ]:
def add_two(x): #adding two to the x value
    return x+2

In [ ]:
add_two(5) #5+2

7

In [ ]:
square(add_two(5)) #square root of 7 

49

### Logical Branching

In [ ]:
choice = "apple" #choosing between aples or oranges 

In [ ]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [ ]:
choice = "orange" #command for orange choice 

In [ ]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [ ]:
choice = "apple"

In [ ]:
if choice == "apple": #commands for thank you, shop again. 

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [ ]:
choice = input("Please enter your choice (i.e. apple): ") #command for the input and choosing between orange or apples

In [ ]:
choice

In [ ]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

#### Coins

In [ ]:
np.random.random() #random flip coin

In [ ]:
np.random.random() > 0.5 #less than 0.5 flip coin

In [ ]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [ ]:
flip_coin()

### Graphics Output

In [ ]:
from IPython.core.display import display, HTML #starter

In [ ]:
display(HTML('<h1>Hello, world!</h1>'))

In [ ]:
def coin(): #random 2 sides 
  return np.random.randint(2)

In [ ]:
coin()

In [ ]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">')) #Url for coin flip 

In [ ]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg' #url for heads
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg' #url for tails 

In [ ]:
def show_img(img): #to display both images 
  display(HTML('<img src=' + img + '>'))

In [ ]:
show_img(heads)

In [ ]:
show_img(tails)

In [ ]:
def flip_coin(): #coinflip for heads and tails 

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [ ]:
flip_coin()

In [ ]:
for i in range(5):
    flip_coin()

In [ ]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [ ]:
def shuffle(x):  #confused about this
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [ ]:
a = np.arange(52) #52 cards 

In [ ]:
shuffle(a)

NameError: ignored

In [ ]:
np.random.permutation(52)

### Speed Test

In [ ]:
%%timeit #timer for flip
shuffle(a)

NameError: ignored

In [ ]:
%%timeit
np.random.permutation(52)

In [ ]:
import numpy as np

In [ ]:
np.random.permutation(52) #array of numbers less than 52

array([51, 40, 39,  2, 19, 24, 12,  7, 14, 28,  8, 21, 18, 49, 47, 27,  1,
       44, 10, 16, 42,  3, 43, 31, 46, 29, 38,  4, 23,  5, 50, 35, 41, 36,
       11, 13, 34, 15, 32, 26, 45, 20, 48, 30,  9, 17, 33,  0, 22, 25,  6,
       37])

In [ ]:
cards = np.random.permutation(52) #random for card#52

In [ ]:
cards

array([32,  0, 51, 29, 27, 15, 39, 45, 42, 12, 30, 28, 44, 34, 33, 16, 49,
       47,  6, 22, 40, 24, 10, 21, 11, 23, 41, 48,  5, 36, 13, 46, 31, 17,
        7, 14,  1, 26,  2, 43, 25,  4, 35, 18,  8, 37, 50,  9,  3, 38, 20,
       19])

In [ ]:
cards[0] #value of card 0

32

In [ ]:
cards[1] #value of the card 

0

In [ ]:
cards[2] #value of card #2

51

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'> 
#image of play cards

In [ ]:
np.arange(52).reshape(4,13)  #array for 52

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [ ]:
np.arange(52).reshape(4,13)%13 #array of numbers less than 13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
suits = ['Clubs','Spades','Hearts','Diamonds'] #how to distinguish each card with suits and names 
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [ ]:
def card_name(card_number): #13 suit and name cards 
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [ ]:
card_name(0) 

'Ace of Clubs'

In [ ]:
card_name(51)

'King of Diamonds'

In [ ]:
cards = np.random.permutation(52) 

In [ ]:
top_of_deck         = card_name(cards[0])  #top, middle, and last card in the deck 
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [ ]:
top_of_deck, second_card_in_deck, last_card_in_deck #the specific card 

('Three of Hearts', 'Nine of Diamonds', 'Ten of Hearts')

In [ ]:
for i in range(5): #range of 5 cards 
    print(card_name(cards[i]))

Four of Spades
Six of Diamonds
Ace of Diamonds
Eight of Clubs
Three of Diamonds


In [ ]:
for i in range(15): #array of 15 card names 
    print(card_name(cards[i]))

Seven of Hearts
Ace of Clubs
King of Diamonds
Four of Hearts
Two of Hearts
Three of Spades
Ace of Diamonds
Seven of Diamonds
Four of Diamonds
King of Clubs
Five of Hearts
Three of Hearts
Six of Diamonds
Nine of Hearts
Eight of Hearts


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [ ]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/" #url for image 
card_url_tail = ".png"

In [ ]:
suit = ['k','p','s','l'] #initials for each card with number 
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [ ]:
i = np.random.randint(4) #random value for i and j 
j = np.random.randint(13)

In [ ]:
i,j  #values 

(0, 11)

In [ ]:
suit[i] #command for king card

'k'

In [ ]:
card[j]

'q'

In [ ]:
from IPython.core.display import display, HTML

In [ ]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [ ]:
img = card_url_head + suit[i] + card[j] + card_url_tail #adding the head, king, and jack card

In [ ]:
show_img(img) #queen card

In [ ]:
def card_image(card_number): #card number for both cards witha  a percentage of 13
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [ ]:
card_image(3) #command for 4

'k4'

In [ ]:
img = card_url_head + card_image(3) + card_url_tail 

In [ ]:
show_img(img) #image of 

In [ ]:
for i in range(52): #52images of cards with heads and tails
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)